version: '3.4'

services:
  app:
    build: .
    depends_on:
      - db
      - adminer
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: admin
      POSTGRES_DB: contacts_app
      PG_DATA: /var/lib/postgresql/data/db-data/
      PORT: 3000
      AWS_ACCESS_KEY_ID: AKIATD2VUQXJZMQUXCP2
      AWS_SECRET_ACCESS_KEY: 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
      AWS_DEFAULT_REGION: sa-east-1
    command: yarn start
    ports:
      - "3000:3000"
  db:
    image: postgres
    restart: always
    volumes:
      - docker-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  docker-data: